/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AppointmentStatusService } from "../appointmentStatus.service";
import { AppointmentStatusCreateInput } from "./AppointmentStatusCreateInput";
import { AppointmentStatus } from "./AppointmentStatus";
import { AppointmentStatusFindManyArgs } from "./AppointmentStatusFindManyArgs";
import { AppointmentStatusWhereUniqueInput } from "./AppointmentStatusWhereUniqueInput";
import { AppointmentStatusUpdateInput } from "./AppointmentStatusUpdateInput";

export class AppointmentStatusControllerBase {
  constructor(protected readonly service: AppointmentStatusService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AppointmentStatus })
  async createAppointmentStatus(
    @common.Body() data: AppointmentStatusCreateInput
  ): Promise<AppointmentStatus> {
    return await this.service.createAppointmentStatus({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AppointmentStatus] })
  @ApiNestedQuery(AppointmentStatusFindManyArgs)
  async appointmentStatuses(
    @common.Req() request: Request
  ): Promise<AppointmentStatus[]> {
    const args = plainToClass(AppointmentStatusFindManyArgs, request.query);
    return this.service.appointmentStatuses({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AppointmentStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async appointmentStatus(
    @common.Param() params: AppointmentStatusWhereUniqueInput
  ): Promise<AppointmentStatus | null> {
    const result = await this.service.appointmentStatus({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AppointmentStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAppointmentStatus(
    @common.Param() params: AppointmentStatusWhereUniqueInput,
    @common.Body() data: AppointmentStatusUpdateInput
  ): Promise<AppointmentStatus | null> {
    try {
      return await this.service.updateAppointmentStatus({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AppointmentStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAppointmentStatus(
    @common.Param() params: AppointmentStatusWhereUniqueInput
  ): Promise<AppointmentStatus | null> {
    try {
      return await this.service.deleteAppointmentStatus({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
