/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PaymentHistory } from "./PaymentHistory";
import { PaymentHistoryCountArgs } from "./PaymentHistoryCountArgs";
import { PaymentHistoryFindManyArgs } from "./PaymentHistoryFindManyArgs";
import { PaymentHistoryFindUniqueArgs } from "./PaymentHistoryFindUniqueArgs";
import { CreatePaymentHistoryArgs } from "./CreatePaymentHistoryArgs";
import { UpdatePaymentHistoryArgs } from "./UpdatePaymentHistoryArgs";
import { DeletePaymentHistoryArgs } from "./DeletePaymentHistoryArgs";
import { PaymentHistoryService } from "../paymentHistory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PaymentHistory)
export class PaymentHistoryResolverBase {
  constructor(
    protected readonly service: PaymentHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PaymentHistory",
    action: "read",
    possession: "any",
  })
  async _paymentHistoriesMeta(
    @graphql.Args() args: PaymentHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PaymentHistory])
  @nestAccessControl.UseRoles({
    resource: "PaymentHistory",
    action: "read",
    possession: "any",
  })
  async paymentHistories(
    @graphql.Args() args: PaymentHistoryFindManyArgs
  ): Promise<PaymentHistory[]> {
    return this.service.paymentHistories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PaymentHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PaymentHistory",
    action: "read",
    possession: "own",
  })
  async paymentHistory(
    @graphql.Args() args: PaymentHistoryFindUniqueArgs
  ): Promise<PaymentHistory | null> {
    const result = await this.service.paymentHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PaymentHistory)
  @nestAccessControl.UseRoles({
    resource: "PaymentHistory",
    action: "create",
    possession: "any",
  })
  async createPaymentHistory(
    @graphql.Args() args: CreatePaymentHistoryArgs
  ): Promise<PaymentHistory> {
    return await this.service.createPaymentHistory({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PaymentHistory)
  @nestAccessControl.UseRoles({
    resource: "PaymentHistory",
    action: "update",
    possession: "any",
  })
  async updatePaymentHistory(
    @graphql.Args() args: UpdatePaymentHistoryArgs
  ): Promise<PaymentHistory | null> {
    try {
      return await this.service.updatePaymentHistory({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PaymentHistory)
  @nestAccessControl.UseRoles({
    resource: "PaymentHistory",
    action: "delete",
    possession: "any",
  })
  async deletePaymentHistory(
    @graphql.Args() args: DeletePaymentHistoryArgs
  ): Promise<PaymentHistory | null> {
    try {
      return await this.service.deletePaymentHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
