/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AuthToken } from "./AuthToken";
import { AuthTokenCountArgs } from "./AuthTokenCountArgs";
import { AuthTokenFindManyArgs } from "./AuthTokenFindManyArgs";
import { AuthTokenFindUniqueArgs } from "./AuthTokenFindUniqueArgs";
import { CreateAuthTokenArgs } from "./CreateAuthTokenArgs";
import { UpdateAuthTokenArgs } from "./UpdateAuthTokenArgs";
import { DeleteAuthTokenArgs } from "./DeleteAuthTokenArgs";
import { AuthTokenService } from "../authToken.service";
@graphql.Resolver(() => AuthToken)
export class AuthTokenResolverBase {
  constructor(protected readonly service: AuthTokenService) {}

  async _authTokensMeta(
    @graphql.Args() args: AuthTokenCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AuthToken])
  async authTokens(
    @graphql.Args() args: AuthTokenFindManyArgs
  ): Promise<AuthToken[]> {
    return this.service.authTokens(args);
  }

  @graphql.Query(() => AuthToken, { nullable: true })
  async authToken(
    @graphql.Args() args: AuthTokenFindUniqueArgs
  ): Promise<AuthToken | null> {
    const result = await this.service.authToken(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AuthToken)
  async createAuthToken(
    @graphql.Args() args: CreateAuthTokenArgs
  ): Promise<AuthToken> {
    return await this.service.createAuthToken({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AuthToken)
  async updateAuthToken(
    @graphql.Args() args: UpdateAuthTokenArgs
  ): Promise<AuthToken | null> {
    try {
      return await this.service.updateAuthToken({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AuthToken)
  async deleteAuthToken(
    @graphql.Args() args: DeleteAuthTokenArgs
  ): Promise<AuthToken | null> {
    try {
      return await this.service.deleteAuthToken(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
