/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RegistrationTokenService } from "../registrationToken.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RegistrationTokenCreateInput } from "./RegistrationTokenCreateInput";
import { RegistrationToken } from "./RegistrationToken";
import { RegistrationTokenFindManyArgs } from "./RegistrationTokenFindManyArgs";
import { RegistrationTokenWhereUniqueInput } from "./RegistrationTokenWhereUniqueInput";
import { RegistrationTokenUpdateInput } from "./RegistrationTokenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RegistrationTokenControllerBase {
  constructor(
    protected readonly service: RegistrationTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RegistrationToken })
  @nestAccessControl.UseRoles({
    resource: "RegistrationToken",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRegistrationToken(
    @common.Body() data: RegistrationTokenCreateInput
  ): Promise<RegistrationToken> {
    return await this.service.createRegistrationToken({
      data: data,
      select: {
        createdAt: true,
        dateCreated: true,
        dateExpires: true,
        id: true,
        phone: true,
        token: true,
        updatedAt: true,
        used: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RegistrationToken] })
  @ApiNestedQuery(RegistrationTokenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RegistrationToken",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async registrationTokens(
    @common.Req() request: Request
  ): Promise<RegistrationToken[]> {
    const args = plainToClass(RegistrationTokenFindManyArgs, request.query);
    return this.service.registrationTokens({
      ...args,
      select: {
        createdAt: true,
        dateCreated: true,
        dateExpires: true,
        id: true,
        phone: true,
        token: true,
        updatedAt: true,
        used: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RegistrationToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RegistrationToken",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async registrationToken(
    @common.Param() params: RegistrationTokenWhereUniqueInput
  ): Promise<RegistrationToken | null> {
    const result = await this.service.registrationToken({
      where: params,
      select: {
        createdAt: true,
        dateCreated: true,
        dateExpires: true,
        id: true,
        phone: true,
        token: true,
        updatedAt: true,
        used: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RegistrationToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RegistrationToken",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRegistrationToken(
    @common.Param() params: RegistrationTokenWhereUniqueInput,
    @common.Body() data: RegistrationTokenUpdateInput
  ): Promise<RegistrationToken | null> {
    try {
      return await this.service.updateRegistrationToken({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dateCreated: true,
          dateExpires: true,
          id: true,
          phone: true,
          token: true,
          updatedAt: true,
          used: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RegistrationToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RegistrationToken",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRegistrationToken(
    @common.Param() params: RegistrationTokenWhereUniqueInput
  ): Promise<RegistrationToken | null> {
    try {
      return await this.service.deleteRegistrationToken({
        where: params,
        select: {
          createdAt: true,
          dateCreated: true,
          dateExpires: true,
          id: true,
          phone: true,
          token: true,
          updatedAt: true,
          used: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
