/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ServiceTimeSlot } from "./ServiceTimeSlot";
import { ServiceTimeSlotCountArgs } from "./ServiceTimeSlotCountArgs";
import { ServiceTimeSlotFindManyArgs } from "./ServiceTimeSlotFindManyArgs";
import { ServiceTimeSlotFindUniqueArgs } from "./ServiceTimeSlotFindUniqueArgs";
import { CreateServiceTimeSlotArgs } from "./CreateServiceTimeSlotArgs";
import { UpdateServiceTimeSlotArgs } from "./UpdateServiceTimeSlotArgs";
import { DeleteServiceTimeSlotArgs } from "./DeleteServiceTimeSlotArgs";
import { ServiceTimeSlotService } from "../serviceTimeSlot.service";
@graphql.Resolver(() => ServiceTimeSlot)
export class ServiceTimeSlotResolverBase {
  constructor(protected readonly service: ServiceTimeSlotService) {}

  async _serviceTimeSlotsMeta(
    @graphql.Args() args: ServiceTimeSlotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ServiceTimeSlot])
  async serviceTimeSlots(
    @graphql.Args() args: ServiceTimeSlotFindManyArgs
  ): Promise<ServiceTimeSlot[]> {
    return this.service.serviceTimeSlots(args);
  }

  @graphql.Query(() => ServiceTimeSlot, { nullable: true })
  async serviceTimeSlot(
    @graphql.Args() args: ServiceTimeSlotFindUniqueArgs
  ): Promise<ServiceTimeSlot | null> {
    const result = await this.service.serviceTimeSlot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ServiceTimeSlot)
  async createServiceTimeSlot(
    @graphql.Args() args: CreateServiceTimeSlotArgs
  ): Promise<ServiceTimeSlot> {
    return await this.service.createServiceTimeSlot({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ServiceTimeSlot)
  async updateServiceTimeSlot(
    @graphql.Args() args: UpdateServiceTimeSlotArgs
  ): Promise<ServiceTimeSlot | null> {
    try {
      return await this.service.updateServiceTimeSlot({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ServiceTimeSlot)
  async deleteServiceTimeSlot(
    @graphql.Args() args: DeleteServiceTimeSlotArgs
  ): Promise<ServiceTimeSlot | null> {
    try {
      return await this.service.deleteServiceTimeSlot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
