/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ServicePackageService } from "../servicePackage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ServicePackageCreateInput } from "./ServicePackageCreateInput";
import { ServicePackage } from "./ServicePackage";
import { ServicePackageFindManyArgs } from "./ServicePackageFindManyArgs";
import { ServicePackageWhereUniqueInput } from "./ServicePackageWhereUniqueInput";
import { ServicePackageUpdateInput } from "./ServicePackageUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ServicePackageControllerBase {
  constructor(
    protected readonly service: ServicePackageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServicePackage })
  @nestAccessControl.UseRoles({
    resource: "ServicePackage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createServicePackage(
    @common.Body() data: ServicePackageCreateInput
  ): Promise<ServicePackage> {
    return await this.service.createServicePackage({
      data: data,
      select: {
        createdAt: true,
        description: true,
        feeFixed: true,
        feePercentage: true,
        fkServiceType: true,
        hidden: true,
        id: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ServicePackage] })
  @ApiNestedQuery(ServicePackageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServicePackage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async servicePackages(
    @common.Req() request: Request
  ): Promise<ServicePackage[]> {
    const args = plainToClass(ServicePackageFindManyArgs, request.query);
    return this.service.servicePackages({
      ...args,
      select: {
        createdAt: true,
        description: true,
        feeFixed: true,
        feePercentage: true,
        fkServiceType: true,
        hidden: true,
        id: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServicePackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServicePackage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async servicePackage(
    @common.Param() params: ServicePackageWhereUniqueInput
  ): Promise<ServicePackage | null> {
    const result = await this.service.servicePackage({
      where: params,
      select: {
        createdAt: true,
        description: true,
        feeFixed: true,
        feePercentage: true,
        fkServiceType: true,
        hidden: true,
        id: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServicePackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServicePackage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateServicePackage(
    @common.Param() params: ServicePackageWhereUniqueInput,
    @common.Body() data: ServicePackageUpdateInput
  ): Promise<ServicePackage | null> {
    try {
      return await this.service.updateServicePackage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          feeFixed: true,
          feePercentage: true,
          fkServiceType: true,
          hidden: true,
          id: true,
          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServicePackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServicePackage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteServicePackage(
    @common.Param() params: ServicePackageWhereUniqueInput
  ): Promise<ServicePackage | null> {
    try {
      return await this.service.deleteServicePackage({
        where: params,
        select: {
          createdAt: true,
          description: true,
          feeFixed: true,
          feePercentage: true,
          fkServiceType: true,
          hidden: true,
          id: true,
          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
