/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SmsRequest } from "./SmsRequest";
import { SmsRequestCountArgs } from "./SmsRequestCountArgs";
import { SmsRequestFindManyArgs } from "./SmsRequestFindManyArgs";
import { SmsRequestFindUniqueArgs } from "./SmsRequestFindUniqueArgs";
import { CreateSmsRequestArgs } from "./CreateSmsRequestArgs";
import { UpdateSmsRequestArgs } from "./UpdateSmsRequestArgs";
import { DeleteSmsRequestArgs } from "./DeleteSmsRequestArgs";
import { SmsRequestService } from "../smsRequest.service";
@graphql.Resolver(() => SmsRequest)
export class SmsRequestResolverBase {
  constructor(protected readonly service: SmsRequestService) {}

  async _smsRequestsMeta(
    @graphql.Args() args: SmsRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SmsRequest])
  async smsRequests(
    @graphql.Args() args: SmsRequestFindManyArgs
  ): Promise<SmsRequest[]> {
    return this.service.smsRequests(args);
  }

  @graphql.Query(() => SmsRequest, { nullable: true })
  async smsRequest(
    @graphql.Args() args: SmsRequestFindUniqueArgs
  ): Promise<SmsRequest | null> {
    const result = await this.service.smsRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SmsRequest)
  async createSmsRequest(
    @graphql.Args() args: CreateSmsRequestArgs
  ): Promise<SmsRequest> {
    return await this.service.createSmsRequest({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => SmsRequest)
  async updateSmsRequest(
    @graphql.Args() args: UpdateSmsRequestArgs
  ): Promise<SmsRequest | null> {
    try {
      return await this.service.updateSmsRequest({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SmsRequest)
  async deleteSmsRequest(
    @graphql.Args() args: DeleteSmsRequestArgs
  ): Promise<SmsRequest | null> {
    try {
      return await this.service.deleteSmsRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
