/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProfessionalPaymentsService } from "../professionalPayments.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProfessionalPaymentsCreateInput } from "./ProfessionalPaymentsCreateInput";
import { ProfessionalPayments } from "./ProfessionalPayments";
import { ProfessionalPaymentsFindManyArgs } from "./ProfessionalPaymentsFindManyArgs";
import { ProfessionalPaymentsWhereUniqueInput } from "./ProfessionalPaymentsWhereUniqueInput";
import { ProfessionalPaymentsUpdateInput } from "./ProfessionalPaymentsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProfessionalPaymentsControllerBase {
  constructor(
    protected readonly service: ProfessionalPaymentsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProfessionalPayments })
  @nestAccessControl.UseRoles({
    resource: "ProfessionalPayments",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProfessionalPayments(
    @common.Body() data: ProfessionalPaymentsCreateInput
  ): Promise<ProfessionalPayments> {
    return await this.service.createProfessionalPayments({
      data: data,
      select: {
        createdAt: true,
        fkAppointment: true,
        fkProfessional: true,
        id: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProfessionalPayments] })
  @ApiNestedQuery(ProfessionalPaymentsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProfessionalPayments",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async professionalPaymentsItems(
    @common.Req() request: Request
  ): Promise<ProfessionalPayments[]> {
    const args = plainToClass(ProfessionalPaymentsFindManyArgs, request.query);
    return this.service.professionalPaymentsItems({
      ...args,
      select: {
        createdAt: true,
        fkAppointment: true,
        fkProfessional: true,
        id: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProfessionalPayments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfessionalPayments",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async professionalPayments(
    @common.Param() params: ProfessionalPaymentsWhereUniqueInput
  ): Promise<ProfessionalPayments | null> {
    const result = await this.service.professionalPayments({
      where: params,
      select: {
        createdAt: true,
        fkAppointment: true,
        fkProfessional: true,
        id: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProfessionalPayments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfessionalPayments",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProfessionalPayments(
    @common.Param() params: ProfessionalPaymentsWhereUniqueInput,
    @common.Body() data: ProfessionalPaymentsUpdateInput
  ): Promise<ProfessionalPayments | null> {
    try {
      return await this.service.updateProfessionalPayments({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fkAppointment: true,
          fkProfessional: true,
          id: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProfessionalPayments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfessionalPayments",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProfessionalPayments(
    @common.Param() params: ProfessionalPaymentsWhereUniqueInput
  ): Promise<ProfessionalPayments | null> {
    try {
      return await this.service.deleteProfessionalPayments({
        where: params,
        select: {
          createdAt: true,
          fkAppointment: true,
          fkProfessional: true,
          id: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
